# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster_problem.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cluster_vrp.Matrix" do
    repeated :time, :float, 1
    repeated :distance, :float, 2
  end
  add_message "cluster_vrp.Location" do
    optional :lat, :float, 1
    optional :lon, :float, 2
    optional :matrix_index, :int32, 3
  end
  add_message "cluster_vrp.Service" do
    optional :name, :string, 1
    repeated :quantities, :float, 2
    optional :duration, :uint32, 3
    repeated :vehicle_indices, :int32, 4
    optional :location, :message, 5, "cluster_vrp.Location"
  end
  add_message "cluster_vrp.Capacity" do
    optional :limit, :float, 1
    optional :load, :float, 2
  end
  add_message "cluster_vrp.Vehicle" do
    optional :name, :string, 1
    repeated :capacities, :message, 2, "cluster_vrp.Capacity"
    optional :start_location, :message, 3, "cluster_vrp.Location"
    optional :end_location, :message, 4, "cluster_vrp.Location"
    optional :duration, :int64, 5
    optional :duration_load, :int64, 6
  end
  add_message "cluster_vrp.Solution" do
    repeated :assignement, :int32, 1
  end
  add_message "cluster_vrp.Options" do
    optional :intermediate_states, :bool, 1
    optional :distance, :string, 2
    optional :cut_index, :int32, 3
  end
  add_message "cluster_vrp.Problem" do
    optional :options, :message, 1, "cluster_vrp.Options"
    repeated :vehicles, :message, 2, "cluster_vrp.Vehicle"
    repeated :services, :message, 3, "cluster_vrp.Service"
    repeated :matrices, :message, 4, "cluster_vrp.Matrix"
    repeated :solutions, :message, 5, "cluster_vrp.Solution"
  end
end

module ClusterVrp
  Matrix = Google::Protobuf::DescriptorPool.generated_pool.lookup("cluster_vrp.Matrix").msgclass
  Location = Google::Protobuf::DescriptorPool.generated_pool.lookup("cluster_vrp.Location").msgclass
  Service = Google::Protobuf::DescriptorPool.generated_pool.lookup("cluster_vrp.Service").msgclass
  Capacity = Google::Protobuf::DescriptorPool.generated_pool.lookup("cluster_vrp.Capacity").msgclass
  Vehicle = Google::Protobuf::DescriptorPool.generated_pool.lookup("cluster_vrp.Vehicle").msgclass
  Solution = Google::Protobuf::DescriptorPool.generated_pool.lookup("cluster_vrp.Solution").msgclass
  Options = Google::Protobuf::DescriptorPool.generated_pool.lookup("cluster_vrp.Options").msgclass
  Problem = Google::Protobuf::DescriptorPool.generated_pool.lookup("cluster_vrp.Problem").msgclass
end
